export const languages = [
  { id: 45, name: "Assembly (NASM 2.14.02)", extension: "asm" },
  { id: 46, name: "Bash (5.0.0)", extension: "sh" },
  { id: 47, name: "Basic (FBC 1.07.1)", extension: "bas" },
  { id: 103, name: "C (GCC 14.1.0)", extension: "c" },
  { id: 105, name: "C++ (GCC 14.1.0)", extension: "cpp" },
  { id: 86, name: "Clojure (1.10.1)", extension: "clj" },
  { id: 51, name: "C# (Mono 6.6.0.161)", extension: "cs" },
  { id: 77, name: "COBOL (GnuCOBOL 2.2)", extension: "cob" },
  { id: 55, name: "Common Lisp (SBCL 2.0.0)", extension: "lisp" },
  { id: 90, name: "Dart (2.19.2)", extension: "dart" },
  { id: 56, name: "D (DMD 2.089.1)", extension: "d" },
  { id: 57, name: "Elixir (1.9.4)", extension: "ex" },
  { id: 58, name: "Erlang (OTP 22.2)", extension: "erl" },
  { id: 87, name: "F# (.NET Core SDK 3.1.202)", extension: "fs" },
  { id: 59, name: "Fortran (GFortran 9.2.0)", extension: "f90" },
  { id: 107, name: "Go (1.23.5)", extension: "go" },
  { id: 88, name: "Groovy (3.0.3)", extension: "groovy" },
  { id: 61, name: "Haskell (GHC 8.8.1)", extension: "hs" },
  { id: 91, name: "Java (JDK 17.0.6)", extension: "java" },
  { id: 96, name: "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)", extension: "java" }, // uses Java files
  { id: 78, name: "Kotlin (1.3.70)", extension: "kt" },
  { id: 64, name: "Lua (5.3.5)", extension: "lua" },
  { id: 79, name: "Objective-C (Clang 7.0.1)", extension: "m" },
  { id: 65, name: "OCaml (4.09.0)", extension: "ml" },
  { id: 66, name: "Octave (5.1.0)", extension: "m" },
  { id: 67, name: "Pascal (FPC 3.0.4)", extension: "pas" },
  { id: 85, name: "Perl (5.28.1)", extension: "pl" },
  { id: 98, name: "PHP (8.3.11)", extension: "php" },
  { id: 43, name: "Plain Text", extension: "txt" },
  { id: 69, name: "Prolog (GNU Prolog 1.4.5)", extension: "pl" },
  { id: 109, name: "Python (3.13.2)", extension: "py" },
  { id: 99, name: "R (4.4.1)", extension: "r" },
  { id: 72, name: "Ruby (2.7.0)", extension: "rb" },
  { id: 108, name: "Rust (1.85.0)", extension: "rs" },
  { id: 81, name: "Scala (2.13.2)", extension: "scala" },
  { id: 82, name: "SQL (SQLite 3.27.2)", extension: "sql" },
  { id: 83, name: "Swift (5.2.3)", extension: "swift" },
  { id: 101, name: "TypeScript (5.6.2)", extension: "ts" },
  { id: 84, name: "Visual Basic.Net (vbnc 0.0.0.5943)", extension: "vb" },
  { id: 63, name: "JavaScript (Node.js 12.14.0)", extension: "js" },
];