# GitHub Actions CI/CD with Secrets
name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Frontend with Secrets
        run: |
          docker build \
            --build-arg VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
            --build-arg VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }} \
            --build-arg VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }} \
            --build-arg VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }} \
            --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} \
            --build-arg VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }} \
            --build-arg VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }} \
            --build-arg VITE_COMPILER_API_BASE=https://your-backend.com \
            -t frontend .

      - name: Build Backend with Secrets
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            --build-arg PORT=5000 \
            --build-arg RAPID_API_HOST=${{ secrets.RAPID_API_HOST }} \
            --build-arg RAPID_API_KEY=${{ secrets.RAPID_API_KEY }} \
            -f Dockerfile.backend \
            -t backend .

      - name: Push to Registry
        run: |
          docker tag frontend ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
          docker tag backend ${{ secrets.DOCKER_REGISTRY }}/backend:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/backend:latest
